---
version: '3.8'
services:
  ustreamer:
    build: .
    image: reg.growlab.digital/ustreamer:alpine
    # devices:
    #   - /dev/video0:/dev/video0
    command: ustreamer --device=/dev/video0 --host=0.0.0.0 --port=9000
