---
version: '3.8'
services:
  ustreamer:
    build: .
    image: reg.growlab.digital/ustreamer:alpine
    environment:
      LD_LIBRARY_PATH: '/opt/vc/lib'
    devices:
      - /dev/vchiq
      - /dev/video0
    ports:
      - published: 8080
        target: 8080
        protocol: tcp
        mode: host
    command: ustreamer --host 0.0.0.0 --encoder=omx --persistent --workers=4 -q 100 -f 60
